version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.25
    container_name: backend_db
    environment:
      MYSQL_ROOT_PASSWORD: backend-db
      MYSQL_PASSWORD: backend-db
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3366:3306"
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
  api:
    stdin_open: true
    tty: true
    build: .
    container_name: backend
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0' -p 4000"
    volumes:
      - .:/api
    ports:
      - "4000:4000"
    depends_on:
      - db
